version: '2'
services:
  microarray:
    image: dnadave/release_microarray:jan2018
    ports:
      - 8787
    labels:
      io.rancher.container.pull_image: always
    tty: true
    hostname: ${host}
    volumes:
      - /Projects/BIGdata:/data:rw
      - /Projects/data:/ssd:rw
    stdin_open: true
    net: bridge
    privileged: true
    labels:
      #make microarray a global service
      io.rancher.scheduler.global: 'true'
      # make microarray only run on host with specified value:
      io.rancher.scheduler.affinity:host_label: ServerID=${host}
